"use strict";

const settings = {
    blockNumbers: 20,
    rowNumbers: 5,
    gameBoard: null,
    gameScore: null,
    blocks: [],
    checkedBloks: [],
    moves: 0,
    blockImages: [
        img_01.png,
        img_02.png,
        img_03.png,
        img_04.png,
        img_05.png,
        img_06.png,
        img_07.png,
        img_08.png,
        img_09.png,
        img_10.png,
        img_11.png,
        img_12.png,
        img_13.png,
        img_14.png,
        img_15.png,
        img_16.png,
        img_17.png,
        img_18.png,
        img_19.png,
        img_20.png,
        img_21.png,
        img_22.png,
        img_23.png
    ],
}